version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  front: # name of the first service
    hostname: localhost
    build: front # specify the directory of the Dockerfile
    ports:
      - "8181:80" # specify port forewarding
  
  express: #name of the second service
    build: server # specify the directory of the Dockerfile
    ports:
      - "5000:5000" #specify ports forewarding
    links:
      - database # link this service to the database service
    depends_on:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017" # specify port forewarding